name: Fly Deploy Beta
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy cookbook-api-beta
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: ENV=beta ./deploy.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BETA }}